[package]
name="weft-wasm"
version.workspace=true
edition.workspace=true
publish.workspace=true
[lib]
crate-type=["cdylib"]
[features]
truss-postgresql-qualified=["weft-runtime/truss-postgresql-qualified"]
ashlar-databricks-qualified=["weft-runtime/ashlar-databricks-qualified"]
ashlar-databricks-candidate=["weft-runtime/ashlar-databricks-candidate"]
ashlar-databricks-arithmetic=["weft-runtime/ashlar-databricks-arithmetic"]
test-original=["weft-runtime/test-original"]
truss-postgresql-candidate=["weft-runtime/truss-postgresql-candidate"]
test-third=["weft-runtime/test-third"]
[dependencies]
weft-runtime={path="../weft-runtime"}
wasm-bindgen="=0.2.105"
