from pathlib import Path
r=Path('.')
p=r/'crates/weft-core/src/path_ir.rs';s=p.read_text().replace('struct PlanSchema04;','struct PlanSchema04;\n#[jsonschema::validator(path = "../../docs/helix/02-design/contracts/logical-plan-v0.4.1.schema.json")]\nstruct PlanSchema041;');s=s.replace('    pub fn new(p: PlanParts) -> Result<Self> {','    pub fn new(p: PlanParts) -> Result<Self> {Self::new_version(p,false)}\n    pub(crate) fn new_version(p: PlanParts, version041: bool) -> Result<Self> {');s=s.replace('ir_version: "weft-ir/0.4.0",','ir_version: if version041 {"weft-ir/0.4.1"} else {"weft-ir/0.4.0"},');s=s.replace('if !PlanSchema04::is_valid(&value) {','if !(if version041 {PlanSchema041::is_valid(&value)}else{PlanSchema04::is_valid(&value)}) {');s=s.replace('    pub fn outputs(&self)', '    pub(crate) fn ir_version(&self) -> &\'static str {self.ir_version}\n    pub fn outputs(&self)',1);p.write_text(s)
p=r/'crates/weft-core/src/path_application_resolve.rs';s=p.read_text().replace('    })\n    .map_err(|_| {','    }, query.count_star_having)\n    .map_err(|_| {',1);p.write_text(s)
p=r/'crates/weft-core/src/backend03_view.rs';s=p.read_text().replace('    pub fn source(self)', '    pub fn ir_version(self) -> &\'static str {self.plan.ir_version()}\n    pub fn source(self)',1);p.write_text(s)
p=r/'crates/weft-core/src/backend03_registry.rs';s=p.read_text().replace('dialect_profile: "weft-sql/0.4.0".into(),\n            ir_version: "weft-ir/0.4.0".into(),','dialect_profile: if plan.ir_version()=="weft-ir/0.4.1" {"weft-sql/0.4.1"}else{"weft-sql/0.4.0"}.into(),\n            ir_version: plan.ir_version().into(),');p.write_text(s)
s=(r/'crates/weft-core/src/compile04.rs').read_text();start=s.index('#[cfg(test)]');end=s.index('impl Compiler {',start);s=s[:start]+s[end:];s=s.replace('0.4.0','0.4.1').replace('v0.4.schema','v0.4.1.schema').replace('Request04','Request041').replace('crate::path_query::parse(&req.sql)','crate::path_query::parse041(&req.sql)');(r/'crates/weft-core/src/compile041.rs').write_text(s)
p=r/'crates/weft-core/src/compile.rs';s=p.read_text();s+='\n#[path = "compile041.rs"]\npub mod v041;\n';p.write_text(s)
p=r/'crates/weft-core/src/backend03_emission.rs';s=p.read_text();a=s.index('    static VALIDATOR:');b=s.index('\nfn integer()',a);original=s[a:b];new=original.replace('VALIDATOR','VALIDATOR041').replace('0.4.schema','0.4.1.schema');s=s[:a]+'    if value["interfaceVersion"]=="weft-compile/0.4.1" {\n'+new[:-2]+'\n    } else {\n'+original[:-2]+'\n    }\n}\n'+s[b:];s=s.replace('"interfaceVersion":"weft-compile/0.4.0","status":"compiled"','"interfaceVersion":if plan.ir_version()=="weft-ir/0.4.1" {"weft-compile/0.4.1"}else{"weft-compile/0.4.0"},"status":"compiled"').replace('"dialect":"weft-sql/0.4.0","compilerVersion"','"dialect":if plan.ir_version()=="weft-ir/0.4.1" {"weft-sql/0.4.1"}else{"weft-sql/0.4.0"},"compilerVersion"');s=s.replace('"aggregate.havingCountDistinctGreater",','"aggregate.havingCountDistinctGreater",\n                "aggregate.havingCountStarGreater",');p.write_text(s)
