//! Structural observation for complete-value-tree access, before data publication.
use crate::{qualified, Identifier};
pub fn integrity(namespace: &Identifier, state: &str, root: &str) -> String {
    let table = |name| qualified(namespace, &Identifier::new(name).unwrap());
    let nodes = table("row_home_node");
    let payloads = table("row_home_scalar");
    let states = table("row_home_state");
    // UNION visits each native node once and terminates even for corrupt cycles.
    // A connected cycle is impossible with one parent per node and a parentless
    // root; disconnected cycles fail the reachability observation.
    let structural=format!("((SELECT count(*) FROM {states} duplicate_state WHERE duplicate_state.owner_kind={state}.owner_kind AND duplicate_state.object_id={state}.object_id AND duplicate_state.object_type_id={state}.object_type_id AND duplicate_state.property_owner_type_id={state}.property_owner_type_id AND duplicate_state.property_id={state}.property_id)=1 AND (WITH RECURSIVE reachable(node_id) AS (SELECT n.node_id FROM {nodes} n WHERE n.state_id={state}.state_id AND n.node_id={root}.node_id UNION SELECT child.node_id FROM {nodes} child JOIN reachable parent ON child.parent_node_id=parent.node_id WHERE child.state_id={state}.state_id) SELECT NOT EXISTS (SELECT 1 FROM {nodes} n LEFT JOIN reachable r USING(node_id) WHERE n.state_id={state}.state_id AND r.node_id IS NULL) AND NOT EXISTS (SELECT 1 FROM {payloads} p LEFT JOIN {nodes} n ON n.state_id=p.state_id AND n.node_id=p.node_id WHERE p.state_id={state}.state_id AND n.node_id IS NULL) AND NOT EXISTS (SELECT 1 FROM {nodes} n LEFT JOIN {nodes} parent ON parent.state_id=n.state_id AND parent.node_id=n.parent_node_id WHERE n.state_id={state}.state_id AND ((n.node_id={root}.node_id AND (n.parent_node_id IS NOT NULL OR n.slot_kind IS DISTINCT FROM 'root')) OR (n.node_id<>{root}.node_id AND (parent.node_id IS NULL OR parent.value_kind IN ('scalar','null') OR (parent.value_kind='sequence' AND n.slot_kind IS DISTINCT FROM 'sequence') OR (parent.value_kind='map' AND n.slot_kind IS DISTINCT FROM 'map') OR (parent.value_kind IN ('structured','record') AND n.slot_kind IS DISTINCT FROM 'record'))))) AND NOT EXISTS (SELECT 1 FROM {nodes} n WHERE n.state_id={state}.state_id AND (n.value_kind IS NULL OR n.value_kind NOT IN ('scalar','null','sequence','map','structured','record') OR (SELECT count(*) FROM {payloads} p WHERE p.state_id=n.state_id AND p.node_id=n.node_id)<>CASE WHEN n.value_kind='scalar' THEN 1 ELSE 0 END)) AND NOT EXISTS (SELECT 1 FROM {payloads} p WHERE p.state_id={state}.state_id AND (p.scalar_kind IS NULL OR NOT ((p.scalar_kind='string' AND p.text_value IS NOT NULL AND p.boolean_value IS NULL AND p.numeric_value IS NULL) OR (p.scalar_kind='boolean' AND p.boolean_value IS NOT NULL AND p.text_value IS NULL AND p.numeric_value IS NULL) OR (p.scalar_kind IN ('integer','decimal') AND p.numeric_value IS NOT NULL AND p.text_value IS NULL AND p.boolean_value IS NULL))))))");
    let dense=format!("NOT EXISTS (SELECT 1 FROM {nodes} parent LEFT JOIN {nodes} child ON child.state_id=parent.state_id AND child.parent_node_id=parent.node_id WHERE parent.state_id={state}.state_id AND parent.value_kind='sequence' GROUP BY parent.node_id HAVING count(child.node_id)<>count(DISTINCT child.sequence_ordinal) OR COALESCE(min(child.sequence_ordinal),0)<>0 OR COALESCE(max(child.sequence_ordinal),-1)<>count(child.node_id)-1)");
    let slots=format!("NOT EXISTS (SELECT 1 FROM {nodes} n WHERE n.state_id={state}.state_id AND NOT ((n.slot_kind='root' AND n.parent_node_id IS NULL AND n.sequence_ordinal IS NULL AND n.map_key IS NULL AND n.record_field_identity_bytes IS NULL) OR (n.slot_kind='sequence' AND n.parent_node_id IS NOT NULL AND n.sequence_ordinal IS NOT NULL AND n.sequence_ordinal>=0 AND n.map_key IS NULL AND n.record_field_identity_bytes IS NULL) OR (n.slot_kind='map' AND n.parent_node_id IS NOT NULL AND n.map_key IS NOT NULL AND n.sequence_ordinal IS NULL AND n.record_field_identity_bytes IS NULL) OR (n.slot_kind='record' AND n.parent_node_id IS NOT NULL AND n.record_field_identity_bytes IS NOT NULL AND n.sequence_ordinal IS NULL AND n.map_key IS NULL)))");
    format!("({structural} AND {dense} AND {slots})")
}
